# Site
name: "KUCMC"
title: "Memoirs"
description: "Welcome to Kathmandu University Computational Mathematics Club. Learn, Share and Collaborate."
logo: 'assets/images/cmclogo.png'
favicon: 'assets/images/cmclogo.png'
baseurl: '/test'
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: wowthemesnet@gmail.com

# Authors
# Authors
authors:
  president:
    name: Ayam Basyal
    display_name: Ayam Basyal
    avatar: 'assets/images/avatar-sal.png'
    email: ayam@example.com
    web: https://www.example.com/ayam
    twitter: https://twitter.com/ayambasyal
    description: "President of the Club."

  vice_president:
    name: Abhinaash Tiwari
    display_name: Abhinaash Tiwari
    avatar: 'assets/images/avatar-sal.png'
    email: abhinaash@example.com
    web: https://www.example.com/abhinaash
    twitter: https://twitter.com/abhinaashtiwari
    description: "Vice President of the Club."

  general_secretary:
    name: Ruby Shrestha
    display_name: Ruby Shrestha
    avatar: 'assets/images/committee/ruby.png'
    email: ruby@example.com
    web: https://www.example.com/ruby
    twitter: https://twitter.com/rubyshrestha
    description: "General Secretary of the Club."

  club_secretary:
    name: Hritik Chaudhary
    display_name: Hritik Chaudhary
    avatar: 'assets/images/avatar-sal.png'
    email: hritik@example.com
    web: https://www.example.com/hritik
    twitter: https://twitter.com/hritikchaudhary
    description: "Club Secretary of the Club."

  treasurer:
    name: Avash Pradhan
    display_name: Avash Pradhan
    avatar: 'assets/images/committee/avash.png'
    email: avash@example.com
    web: https://www.example.com/avash
    twitter: https://twitter.com/avashpradhan
    description: "Treasurer of the Club."

  asst_treasurer:
    name: Sandesh Sapkota
    display_name: Sandesh Sapkota
    avatar: 'assets/images/avatar-sal.png'
    email: sandesh@example.com
    web: https://www.example.com/sandesh
    twitter: https://twitter.com/sandeshsapkota
    description: "Assistant Treasurer of the Club."

  technical_head:
    name: Sashuv Kafle
    display_name: Sashuv Kafle
    avatar: 'assets/images/committee/sashuv.png'
    email: sashuv@example.com
    web: https://www.example.com/sashuv
    twitter: https://twitter.com/sashuvkafle
    description: "Technical Head of the Club."

  executive_member_1:
    name: Shambhav Rajamajhi
    display_name: Shambhav Rajamajhi
    avatar: 'assets/images/avatar-sal.png'
    email: shambhav@example.com
    web: https://www.example.com/shambhav
    twitter: https://twitter.com/shambhav
    description: "Executive Member of the Club."

  executive_member_2:
    name: Supriya Baniya
    display_name: Supriya Baniya
    avatar: 'assets/images/committee/supriya.png'
    email: supriya@example.com
    web: https://www.example.com/supriya
    twitter: https://twitter.com/supriyabaniya
    description: "Executive Member of the Club."

  executive_member_3:
    name: Priya Kumari Jaiswal
    display_name: Priya Kumari Jaiswal
    avatar: 'assets/images/committee/priya.png'
    email: priya@example.com
    web: https://www.example.com/priya
    twitter: https://twitter.com/priyakumari
    description: "Executive Member of the Club."

  executive_member_4:
    name: Pratik Ray
    display_name: Pratik Ray
    avatar: 'assets/images/avatar-sal.png'
    email: pratik@example.com
    web: https://www.example.com/pratik
    twitter: https://twitter.com/pratikray
    description: "Executive Member of the Club."

  executive_member_5:
    name: Priti Tamang
    display_name: Priti Tamang
    avatar: 'assets/images/avatar-sal.png'
    email: priti@example.com
    web: https://www.example.com/priti
    twitter: https://twitter.com/prititamang
    description: "Executive Member of the Club."

  club_advisor_1:
    name: Mukesh Tiwari
    display_name: Mukesh Tiwari
    avatar: 'assets/images/avatar-sal.png'
    email: mukesh@example.com
    web: https://www.example.com/mukesh
    twitter: https://twitter.com/mukesh
    description: "Club Advisor."

  club_advisor_2:
    name: Prof. Dr. Rabindra Kayastha
    display_name: Prof. Dr. Rabindra Kayastha
    avatar: 'assets/images/avatar-sal.png'
    email: rabindra@example.com
    web: https://www.example.com/rabindra
    twitter: https://twitter.com/rabindra
    description: "Club Advisor."

  club_advisor_3:
    name: Dr. Saraswati Acharya
    display_name: Dr. Saraswati Acharya
    avatar: 'assets/images/avatar-sal.png'
    email: saraswati@example.com
    web: https://www.example.com/saraswati
    twitter: https://twitter.com/saraswati
    description: "Club Advisor."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
